In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("US_Accidents_June20_CLEANED4.csv")

In [3]:
for col in df.columns:
    if df[col].dtype == "object":
        le = LabelEncoder()
        df[col].fillna("None", inplace=True)
        le.fit(list(df[col].astype(str).values))
        df[col] = le.transform(list(df[col].astype(str).values))
    else:
        df[col].fillna(-999, inplace=True)

In [3]:
numericData_lst=['Temperature(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','newSeverity','Hour']
df=df[numericData_lst].copy()
df.head()

Temperature(F)  Humidity(%)  Pressure(in)  Visibility(mi)  Wind_Speed(mph)  \
0            35.1         96.0         29.64             9.0              4.6   
1            36.0         89.0         29.65             6.0              3.5   
2            37.9         97.0         29.63             7.0              3.5   
3            34.0        100.0         29.66             7.0              3.5   
4            34.0        100.0         29.66             7.0              3.5   

   newSeverity  Hour  
0            2     7  
1            2     7  
2            2     7  
3            2     7  
4            2     7

In [14]:
df.shape

(1905567, 28)

In [4]:
# Separating out the features
#x = df.loc[:, features].values
# Separating out the target
#y = df.loc[:,['newSeverity']].values
# Standardizing the features
df = df[df.columns.difference(['Unnamed: 0','iforest','newSeverity'])]
x = StandardScaler().fit_transform(df)

In [5]:
x

array([[-0.20383849, -0.901747  , -0.35429061, ..., -0.73208404,
        -1.40914368, -1.35959627],
       [-0.20383849, -0.901747  , -0.35429061, ..., -0.94959426,
        -1.40914368, -1.35959627],
       [-0.20383849,  1.75361069, -0.35429061, ..., -0.94959426,
        -1.40914368, -1.35959627],
       ...,
       [-0.20383849,  0.97853136, -0.35429061, ..., -0.49480016,
        -0.21479554,  0.4096392 ],
       [-0.20383849,  0.60773169,  2.82254162, ..., -0.94959426,
        -0.21479554,  0.4096392 ],
       [-0.20383849, -0.01074777,  2.82254162, ..., -0.94959426,
        -0.21479554,  0.4096392 ]])

In [15]:
from sklearn.decomposition import PCA
numComp = 28
pca = PCA(n_components=numComp)
principalComponents = pca.fit_transform(x)

In [16]:
columns = []
for i in range(1,numComp+1):
    columns.append("PC" + str(i))
columns

['PC1',
 'PC2',
 'PC3',
 'PC4',
 'PC5',
 'PC6',
 'PC7',
 'PC8',
 'PC9',
 'PC10',
 'PC11',
 'PC12',
 'PC13',
 'PC14',
 'PC15',
 'PC16',
 'PC17',
 'PC18',
 'PC19',
 'PC20',
 'PC21',
 'PC22',
 'PC23',
 'PC24',
 'PC25',
 'PC26',
 'PC27',
 'PC28']

In [17]:
principalDf = pd.DataFrame(data = principalComponents, columns = columns)

In [18]:
principalDf

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0       -1.251194 -2.037668  0.589660  1.469504 -0.404653 -0.564070  0.510671   
1        0.325103 -2.365196 -0.577815  1.598801 -1.120177 -0.478135  0.707843   
2        0.064666 -2.421467  0.648730  1.601943 -1.157503 -0.384505 -0.537393   
3        0.001686 -2.280220  0.778639  1.847576 -0.545838 -0.807139  0.460686   
4       -0.000045 -2.280008  0.791655  1.840889 -0.543772 -0.811180  0.474687   
...           ...       ...       ...       ...       ...       ...       ...   
1905562  1.182694  3.481327  0.556761 -1.120341  0.709073 -0.052742  0.339270   
1905563  0.591966  1.961469  0.822183 -0.697648 -0.491437 -0.828962  0.020853   
1905564  1.114094  3.079350  0.996520 -1.017645 -0.796966 -0.691503 -0.712794   
1905565 -1.969104  3.361626  0.544803 -0.448476 -0.575024 -0.210681 -0.168970   
1905566 -3.982229  3.759649 -0.262315 -0.547114 -0.554805 -0.081919 -0.695942   

              PC8       PC9      PC10  ...      PC19      PC20      PC21  \
0       -0.063904  0.610875 -0.368558  ... -0.193779 -0.277943 -0.413574   
1        0.317310  0.138488 -0.108484  ... -0.908047 -0.571711  0.668175   
2        0.436046  0.455486 -0.414993  ... -0.437453 -1.821839  0.760045   
3        0.173282  0.612207 -0.484792  ... -0.194573 -0.962637  0.604788   
4        0.160524  0.609115 -0.482389  ... -0.193600 -0.966148  0.608117   
...           ...       ...       ...  ...       ...       ...       ...   
1905562 -0.356610  0.352312 -0.487070  ... -0.881014 -0.374664  0.029595   
1905563 -0.082903  0.100737 -0.302097  ... -0.880883 -0.195621 -0.125020   
1905564  0.331132 -0.567100 -0.096193  ... -1.205244 -0.522238  0.156201   
1905565 -0.107752  0.089471 -0.295597  ... -0.496615 -1.193370 -2.434581   
1905566  0.386510 -0.109263 -0.139689  ... -0.794192 -0.267917 -1.400298   

             PC22      PC23      PC24      PC25      PC26      PC27      PC28  
0        1.563527  1.340647  0.431742  0.149230 -0.510649  1.151974 -1.106277  
1        0.918226 -0.120109  1.693105 -0.357249 -0.606311 -0.145176  0.067674  
2        0.532498  1.092718  0.723714 -0.060600 -0.809933 -0.141124  0.074042  
3        0.400025  1.002546  0.530729  0.224910 -0.811068 -0.169382  0.080409  
4        0.407814  1.002234  0.533070  0.224512 -0.811503 -0.169417  0.080329  
...           ...       ...       ...       ...       ...       ...       ...  
1905562  0.132812  0.483560  0.069670 -0.642091 -0.033572  0.030536 -0.020968  
1905563  0.022995  0.283875  0.170324  0.932977 -0.215301 -0.086275  0.022603  
1905564  0.204738 -0.131967 -0.281820 -1.373294  0.172384  0.078011 -0.038237  
1905565  1.200136  0.345689 -0.416713 -0.483879  0.274515  0.391294  1.094916  
1905566  0.548860  0.384580 -0.209526 -0.560407  0.505958 -2.109375 -0.942677  

[1905567 rows x 28 columns]

In [21]:
autovalores = pca.explained_variance_ratio_
autovalores

array([0.11162426, 0.07555983, 0.05658029, 0.0533111 , 0.04976213,
       0.04779933, 0.04001294, 0.0373429 , 0.03631598, 0.03608993,
       0.03580701, 0.03556127, 0.03533065, 0.03485959, 0.03398684,
       0.03346984, 0.03245739, 0.03036202, 0.02842222, 0.02689257,
       0.02355972, 0.02182826, 0.01950445, 0.01910701, 0.01624034,
       0.01453166, 0.00830982, 0.00537065])

In [26]:
suma = 0
for i in range(0,20):
    suma+=autovalores[i]
suma

0.8715480957506744

In [ ]:
for i in autovalores:
    suma+=i

In [ ]:
# vbles booleanas

In [104]:
from sklearn.preprocessing import StandardScaler
features = ['Start_Lat','Start_Lng',
            'Temperature(F)',
            'Humidity(%)',
            'Pressure(in)',
            'Visibility(mi)',
'Wind_Speed(mph)',
'Crossing',
'Give_Way',
'Junction',                    
'Railway',
'Roundabout',
'Stop',
'Traffic_Signal'
           ]

In [130]:
# Separating out the features
x = df.loc[:, features].values
# Separating out the target
y = df.loc[:,['newSeverity']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)

In [131]:
from sklearn.decomposition import PCA
pca = PCA(n_components=7)
principalComponents = pca.fit_transform(x)

In [132]:
principalComponents = pca.fit_transform(x)

In [133]:
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1',
                          'principal component 2',
                          'principal component 3',
                          'principal component 4',
                          'principal component 5',
                          'principal component 6',
                          'principal component 7',
                          
                         ])

In [134]:
principalDf

principal component 1  principal component 2  principal component 3  \
0                    -1.355219               1.613133              -0.140973   
1                    -2.069803               0.266575               0.120109   
2                    -1.756490               1.771136              -0.196063   
3                    -2.374975               0.406161              -0.116135   
4                    -2.512401               0.454787              -0.118465   
...                        ...                    ...                    ...   
2117292               2.508312              -1.680049               0.543579   
2117293               0.786141              -0.982289              -0.108582   
2117294               1.920548              -1.426043              -0.222868   
2117295               1.628362              -1.330277              -0.088174   
2117296               1.643138              -1.326391              -0.217480   

         principal component 4  principal component 5  principal component 6  \
0                    -0.039704              -0.239009              -0.607681   
1                    -0.182177              -0.243456              -0.241512   
2                    -0.299766              -0.316819              -0.660013   
3                    -0.475623              -0.286305              -0.279381   
4                    -0.520216              -0.266586              -0.269245   
...                        ...                    ...                    ...   
2117292              -1.281435              -0.478783              -0.624245   
2117293              -1.121713              -0.085600              -0.216346   
2117294              -1.113782              -0.137112              -0.214402   
2117295              -1.205389              -0.080632              -0.258738   
2117296              -1.161502              -0.036066              -0.204367   

         principal component 7  
0                     0.597105  
1                     0.074644  
2                     0.643606  
3                     0.111716  
4                     0.095584  
...                        ...  
2117292               0.317757  
2117293              -0.044279  
2117294              -0.031611  
2117295              -0.028065  
2117296              -0.070581  

[2117297 rows x 7 columns]

In [135]:
pca.explained_variance_ratio_

array([0.12905952, 0.1089594 , 0.09172921, 0.08044103, 0.07439075,
       0.07342766, 0.07121958])

In [138]:
expl = pca.explained_variance_ratio_ 
print(expl)
print('suma:',sum(expl[0:7]))

[0.12905952 0.1089594  0.09172921 0.08044103 0.07439075 0.07342766
 0.07121958]
suma: 0.6292271432701546


In [ ]:
#Required python packages
#Load the input dataset
#Building the logistic regression for multi-classification
#Implementing the multinomial logistic regression
#Comparing the accuracies

In [ ]:
# Required Python Packages
import pandas as pd
import numpy as np
from sklearn import linear_model #para el modelo de regresion lineal
from sklearn import metrics #calcula la presicion de la data de entrenamiento
from sklearn.cross_validation import train_test_split # dividir data en entrenamiento y test
 
import plotly.graph_objs as go
import plotly.plotly as py  #visualizar los datos
from plotly.graph_objs import *